### ISSUE TITLE
Left mouse button acts as primary click even when invert mouse buttons is on

### ISSUE THREAD

**Issue by Royce551** [alkalinethunder/socially-distant#1]
If the primary mouse button in Windows is set to right, the game still acts as if the left button is the primary mouse button

**Comment by alkalinethunder** [comment]
I am not sure if I can easily implement this behavior short of just adding a setting to the game itself that configures which button is primary.

**Comment by TobiasSN** [comment]
This issue should be closed.

**Comment by Royce551** [comment]
Fixed in recent update (though as far as i know not automatically handled)
